version: 2

project_name: msgpackgen

before:
  hooks:
    - go mod tidy
builds:
  - main: .
    binary: msgpackgen
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
archives:
  - name_template: >-
      {{ .ProjectName }}_{{ tolower .Os }}_
      {{- if eq .Arch "amd64" -}}x86_64
      {{- else if eq .Arch "386" -}}i386
      {{- else -}}{{ .Arch }}{{- end -}}
      {{- if .Arm -}}v{{ .Arm }}{{- end -}}

    format_overrides:
      - goos: windows
        formats: [zip]
release:
  prerelease: auto