name: release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

env:
  GOPATH: ${{ github.workspace }}
  WORKSPACE: ${{ github.workspace }}/src/github.com/${{ github.repository }}

jobs:
  goreleaser:
    defaults:
      run:
        working-directory: ${{ env.WORKSPACE }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
          path: ${{ env.WORKSPACE }}
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}